name: zebrautil
description: A Flutter plugin for discovering and printing to Zebra label printers over Bluetooth (MFi) and Wi-Fi (TCP), with helpers for ZPL/CPCL.
version: 1.4.43
homepage: https://github.com/ovidiuomniaz/zebra_printer_utility
repository: https://github.com/ovidiuomniaz/zebra_printer_utility
issue_tracker: https://github.com/ovidiuomniaz/zebra_printer_utility/issues

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  plugin:
    platforms:
      android:
        package: com.rubdev.zebrautil
        pluginClass: ZebraUtilPlugin
      ios:
        pluginClass: ZebraUtilPlugin
